version: "2"
plugins:
  duplication:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 9
  file-lines:
    config:
      threshold: 1000
exclude_patterns:
  - "docs/source"
  - "src/einsteinpy/metric/schwarzschild.py"
