version: 2
jobs:
  quality:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install black isort mypy --quiet
      - run:
          name: check Black style
          command: |
            . venv/bin/activate
            isort -c -rc setup.py src/ -p einsteinpy -sd THIRDPARTY  # This avoids installing einsteinpy
            black src/ setup.py --check
      - run:
          name: check MyPy
          command: |
            . venv/bin/activate
            mypy --ignore-missing-imports --check-untyped-defs --no-strict-optional src/
  test_py35: &test-template  # See https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462/2
    docker:
      - image: circleci/python:3.5

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy --quiet
            pip install . --quiet
            pip install .[dev] --quiet
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            MPLBACKEND=Agg pytest -vv  # Test against installed code (Can use --doctest-modules)
  test_py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test_py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  coverage:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip --quiets
            pip install numpy --quiet
            pip install --editable .[dev] --quiet
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            MPLBACKEND=Agg NUMBA_DISABLE_JIT=1 pytest --cov  # Test against sources
      - run:
          name: publish coverage
          command: |
            . venv/bin/activate
            pip install codecov --quiet
            codecov
  docs:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt update && sudo apt install --no-install-recommends pandoc texlive texlive-latex-extra texlive-fonts-recommended dvipng graphviz
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dev] --quiet
            pip install alabaster
      - run:
          name: build docs
          command: |
            . venv/bin/activate
            sphinx-build -vW -b html docs/source docs-html
      - store_artifacts:
          path: docs-html
          destination: docs-html

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - test_py35:
          requires:
            - quality
      - test_py36:
          requires:
            - quality
      - test_py37:
          requires:
            - quality
      - coverage:
          requires:
            - quality
      - docs:
          requires:
            - test_py35
            - test_py36
            - test_py37
