from einsteinpy.plotting.geodesics.geodesics_scatter import ScatterGeodesicPlotter
from einsteinpy.plotting.geodesics.geodesics_static import StaticGeodesicPlotter
from .mplplotter import MatplotlibPlotter
